### ISSUE TITLE
Improve docs for React - fails with Unautorized on login

### ISSUE THREAD

**Issue by kristianmandrup** [ecerroni/apollo-connector-kit#2]
Great job with this project ;)

I've tried running the React dev server and Apollo server using default settings. On login with the admin user, the server throws an `Unautorized!` error when I login successfully via the username/password login. Is this expected behavior?

Error clearly originates from authenticated (resolver) higher order function

```js
const authenticated = resolver => (parent, args, context, info) => {
  // console.log('context user', context.user);
  if (context.user) {
    return resolver(parent, args, context, info);
  }
  console.log('resolver:authenticated')
  throw new Error(UNAUTHORIZED); // this is gonna be handled in _format-errors
};
```

https://zach.codes/handling-auth-in-graphql-the-right-way/

On login with limited access user `kris`, I get 403: Forbidden (which makes sense)

It is also a bit unclear how to configure the app to use a cookie auth strategy. I can see in my Chrome Dev Tools, that the localstorage is set with two entries and that if I delete them, I'm asked to login again, however I don't see any cookies being set.

I tried to log cookies used on server side in `handleAuthentication`

```js
  if (httpOnly) {
    token = getCookie(req.headers.cookie, JWT.COOKIE.TOKEN.NAME);
    refreshToken = getCookie(req.headers.cookie, JWT.COOKIE.REFRESH_TOKEN.NAME);
    console.log('cookies', {
      token,
      refreshToken
    })
  }
```

From the code it looks like it parses the strategies part of the app config and if httpOnly is set, it will get (and later potentially set) the cookies, however it seems to throw before it gets there...

```json
  "STRATEGIES": {
    "HTTP_ONLY": true,
    "LOCAL_STORAGE": true
  },
```

Please advice. 

In our setup we would like to use cookies and we have a React app on one domain/port talking to a GraphQL server on another domain/port which talks to our API gateway. How do we best pass on the cookie info? I see by default you have a Cors `same origin` configuration. Assume we need to use `include` as outlined in [Apollo auth cookie docs](https://www.apollographql.com/docs/react/recipes/authentication.html#Cookie)

Thanks for an excellent project. Hope we can use it in our project to minimize setup/config effort.
Cheers!

**Comment by ecerroni** [comment]
Hey @kristianmandrup :)
> On login with the admin user, the server throws an Unautorized! error when I login successfully via the username/password login. Is this expected behavior?

The server gets a very first request with either expired or no token at first load. But then the client resend them again before sending the right ones it got from the mutation response. 

I agree that could be confusing and that it might be subject to improvement.

> I tried to log cookies used on server side in handleAuthentication

The server will accept the cookie strategy as well, but you are not able to log it because the client strategy is set to local storage, so no cookies are sent.

To change the client strategy and force it to use cookies you need to set it in `./frontend-react/src/environment/_auth.js`

Change this line:
`export const CLIENT_AUTH_REQUEST_TYPE = AUTH.STRATEGIES.CLIENT.LOCAL_STORAGE;`

to this line:
`export const CLIENT_AUTH_REQUEST_TYPE = AUTH.STRATEGIES.CLIENT.HTTP_ONLY`

Everything should work out of the box and you should see the following under your devTools:
![cookies_client](https://user-images.githubusercontent.com/11174327/46430718-29f17f00-c74a-11e8-9df3-7678067e8286.png)



This is not documented in the readme and I should add it :+1:

**Comment by kristianmandrup** [comment]
Sweet :) Please add some docs next, then keep improving. We really need a better way  to get GraphQL up and running with authentication that covers most of the basic scenarios. Good job!
